mrst=32.7144;% W {bauer_metabolic}
m=2.46; %Mass of the baby. kg
Sa=m^0.75/10.8;% Surface area of the baby. m2
Qmet=mrst*Sa;% Calor específico de la capa central (C_pcore)
cp_co = 3470; % Calor esp% ecífico del core en J/kg·K {young_fisica}
K_c = 0.6;       % Conductividad térmica d%el core (W/m·K) {lemmon_refprop}
rho_c = 1050;    % Densidad del core (kg/m³)
rho_bl = 1060;     % Densidad de la sangre (kg/m³){moggi_hemorreologia}
bf = 0.18*60 / 1000;  % Flujo sanguíneo (m3/kg*s){gomez2014ecocardiografia}
cp_b = 3770;       % Calor específico de la sangre (J/kg·K) {sanchez_biotransferencia}
IV = 3.3e-6;        % Volumen inspirado por kg de masa por segundo (m³/kg·s){yeler2021performance}
cpa = 1005;       % Calor específico del aire (J/kg·K){calor_especifico}
rho_a = 1.2;      % Densidad del aire (kg/m³)
Tex = 36.5+273;     % Temperatura del aire exhalado (K)
Ta = 27+273;      % Temperatura del ambiente (K)
hf_g = 2.343e6;    % Calor de vaporización del agua (J/kg){rios_calor_vaporizacion}
Wex = 44e-6/1.184e-3;      % Humedad del aire exhalado (kg agua/kg aire){intersurgical_humidificacion}
Wa = 0.010;       % Humedad del aire ambiente (kg agua/kg aire)
th_s = 0.005;         % Espesor de los tejidos (m)
rho_s = 1150;         % Densidad de los tejidos (kg/m³)% Cálculo de la masa de los tejidos adyacentes
Vb= m*100e-6; %volumen de sangre m3
ms = th_s * rho_s * Sa;% Cálculo de la masa del core
m_co = m - ms;
mco=m_co
cpa_skin = 3400;      % Calor específico de la piel (J/kg·K){sanchez_biotransferencia}% Cálculo de la masa de la piel
ma = 0.1 * m;         % Masa de la piel (kg)
As = 0.1 * Sa;        % Área en contacto con el colchón (m²)
Kmat = 0.07;          % Conductividad térmica del colchón (W/m·K){din_52612}
thm = 0.04;            % Grosor del colchón (m)
Acv = 0.9 * Sa;         % Área expuesta al aire (m²)
Dsph = 0.12;            % Diámetro característico de la cabeza (m)
Ka = 0.0262;             % Conductividad térmica del aire (W/m·K){propiedades_aire}
Re = 500;               % Número de Reynolds estimado
Pr = 0.71;              % Número de Prandtl del aire
mu_a = 1.8e-5;          % Viscosidad dinámica del aire (Pa·s){jimenez_flujos}
mu_s = 1e3;            % asumida
maire=0.15;% Cálculo del Número de Nusselt
Nu = (2 + (0.4 * Re^(1/2) + 0.06 * Re^(2/3)) * Pr^0.4 * (mu_a/mu_s)^0.25);% Coeficiente de transferencia de calor convectivo
hscv = (Nu * Ka) / Dsph;
hfg = 2.257e6;          % Latent heat of vaporization (J/kg)
age = 0.142;            % Edad en semanas (5 días = 0.142 semanas)
GA = 35;                % Edad gestacional (semanas)
Psat =2300;             % Presión de saturación del vapor (Pa)
rho_w = 1000;           % Densidad del agua (kg/m³)% Cálculo de la tasa de evaporación (Evap)
Evap = 0.15e-9;%{hannouch_heat_transfer}
Ar = 0.555 * Sa;                 % Área expuesta a radiación (m²)
sigma = 5.670e-8;                % Constante de Stefan-Boltzmann (W/m²K⁴)
eps_s = 0.97;                    % Emisividad de la piel
ma = 0.02;       % Masa del aire (kg), valor estimado
rho_a = 1.2;  % Densidad del aire (kg/m³)
v_max = 0.30; % Velocidad máxima del aire (m/s)
A_entrada = 0.01; % Área de entrada de aire (m²) -> Ajustable% Calcular flujo de masa de aire
mdot_a = rho_a * A_entrada * v_max;
Awi = 0.67*0.04*2+0.36*0.04*2;  % Área de contacto con paredes del incubador (m²)
Amat = 0.36*0.67;   % Área total del colchón (m²) -> Ajustable
As = 0.36*0.15;     % Área de la piel del bebé en contacto con el colchón (m²)
Anet = Amat - As;% Parámetros físicos de las paredes del incubador
rho_w = 1060;   % Densidad del material de la pared (kg/m³) -> Ajustar según material
th_w = 0.01;    % Espesor de la pared (m) -> Ajustar según diseño
Awi = 1.2;      % Área de la pared en contacto con el aire (m²) -> Ajustar
hacv=20;% Cálculo de la masa de las paredes
mw = rho_w * th_w * Awi;
kplex = 0.189;
epsilon_w = 0.9;  % Emisividad del material de la pared -> Ajustar
mm = 2.5;       % Masa del colchón (kg) -> Ajustar según datos reales
cpm = 1500;     % Capacidad calorífica específica (J/kg·K) -> Ajustar
cpw=4e7;
Ave=0.0628;
hien = hscv; 
A_tot=1.5112;% Parámetros físicos
D_hum = 2.5e-5;   % Difusividad del vapor de agua en aire (m^2/s)
L_hum = 0.1;      % Longitud característica de la superficie de evaporación (m)
nu_hum = 1.5e-5;  % Viscosidad cinemática del aire (m^2/s)
U_hum = 1e-9;        % Velocidad del aire sobre la superficie (m/s)% Cálculo de números adimensionales
Re_hum = (U_hum * L_hum) / nu_hum;  % Número de Reynolds
Sc_hum = nu_hum / D_hum;            % Número de Schmidt% Parámetros de la correlación de Chilton-Colburn (flujo laminar)
C_hum = 0.664;  
m_hum = 0.5;% Cálculo del coeficiente de transferencia de masa h_m
Sh_hum = C_hum * Re_hum^m_hum * Sc_hum^(1/3);  % Número de Sherwood
h_m_hum = (D_hum / L_hum) * Sh_hum;            % Coeficiente de transferencia de masa (m/s)
A_hum=L_hum*L_hum;
R_hum=461.5;   % Constante del gas para el vapor de agua (J/kg·K)
V_aire=maire/rho_a;
P_atm = 101325;    % Presión atmosférica (Pa)






